name: New Feature For Migration
description: New Feature For Migration Pymahjongutil.
title: "[MIG]: "
labels: ["feature"]
projects: ["taeho-gwon/1"]
assignees: ["taeho-gwon"]
body:
  - type: markdown
    attributes:
      value: |
        **What to migrate**
  - type: textarea
    attributes:
      label: Migration target
      description: Write down the migration target from pymahjongutil
      placeholder: migration target
    validations:
      required: true
